
import pandas as pd
import numpy as np
import uuid
import time
from typing import List
from pathlib import Path

from preprocessing.common_dictionaries import africa_columns_to_change
from preprocessing.common_dictionaries import china_columns_to_change
from preprocessing.common_dictionaries import mit_columns_to_delete
from preprocessing.common_dictionaries import mit_columns_to_change
from preprocessing.common_dictionaries import multiselect_columns_to_delete
from preprocessing.helper_functions import multiselect_encoding
from preprocessing.common_dictionaries import middle_east_columns_to_delete
from preprocessing.common_dictionaries import middle_east_columns_to_change
from preprocessing.common_dictionaries import INDUSTRY_TO_PRACTICE_AREA
from preprocessing.common_dictionaries import REGION_TO_COUNTRIES

from helper_functions import create_screener
from helper_functions import create_screener_without_demo4